import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Gagan - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main className="" style={{height: "900px"}}>
        <Header/>
        <div>
          <h1>Hello World This is Gagndeep</h1>
          <p>lorem oipsijdhfljhljld lorem oipsijdhfljhljldlorem oipsijdhfljhljldlorem oipsijdhfljhljldlorem oipsijdhfljhljldlorem oipsijdhfljhljldlorem oipsijdhfljhljld</p>
        </div>
      </main>

      <footer>
        
      </footer>
    </div>
  )
}
