import Head from 'next/head'
import Header from '../components/Header'
import About from '../components/About'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Gagan - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link href="https://fonts.googleapis.com/css2?family=Great+Vibes&display=swap" rel="stylesheet" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main>
        <Header/>
        <About />
      </main>
    </div>
  )
}
